In [1]:
import cv2 as cv
import numpy as np

In [2]:
img = cv.imread("Animal-image.png")
cv.imshow("Orignal Image", img)
cv.waitKey(0)

-1

In [3]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [4]:
img.shape

(800, 800, 3)

In [5]:
blue_image = img.copy()

In [6]:
blue_image[:,:,1]=0     # Green will be zero
blue_image[:,:,2]=0     # Red will be zero

In [7]:
cv.imshow("Blue Image", blue_image)
cv.imwrite("Blue Image.png", blue_image)
cv.waitKey(0)

-1

In [8]:
green_image = img.copy()

In [9]:
green_image[:,:,0]=0  # Blue will be zero
green_image[:,:,2]=0  # Red will be zero

In [10]:
cv.imshow("Green Image", green_image)
cv.imwrite("Green Image.png", green_image)
cv.waitKey(0)

-1

In [11]:
img[:,:,1]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [12]:
img[:,:,2]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [13]:
red_image = img.copy()

In [14]:
red_image[:,:,0]=0   # Blue will be zero
red_image[:,:,1]=0   # Red will be zero

In [15]:
cv.imshow("Red Image", red_image)
cv.imwrite("Red Image.png", red_image)
cv.waitKey(0)

-1

In [16]:
resized_img = cv.resize(img, (500, 500))
cv.imshow("Resized Image", resized_img)
cv.imwrite("Resized Image.png", resized_img)
cv.waitKey(0)

-1

In [17]:
rescaled_img = cv.resize(img, None, fx=0.5, fy=0.5)
cv.imshow("Rescaled Image", rescaled_img)
cv.imshow("Orignal Image" , img)
cv.imwrite("Rescaled Image.png", rescaled_img)
cv.waitKey(0)

-1

In [18]:
col, row = img.shape[:2]
rotation_matrix = cv.getRotationMatrix2D((col/2, row/2), 60 , 1)
rotated_img = cv.warpAffine(img, rotation_matrix, (col, row))

In [19]:
cv.imshow("rotation Image", rotated_img)
cv.imwrite("rotation Image.png", rotated_img)
cv.waitKey(0)

-1

In [20]:
blurred_img = cv.GaussianBlur(img, (7,7), 2)

In [21]:
cv.imshow("Blurred Image", blurred_img)
cv.imwrite("Blurred Image.png", blurred_img)
cv.waitKey(0)

-1

In [22]:
shared_matrix = np.float32([[1, 0.25, 0], [0, 1, 0]])
shared_img = cv.warpAffine(img, shared_matrix, (col, row))

In [23]:
cv.imshow("Shared Image", shared_img)
cv.imwrite("Shared Image.png", shared_img)
cv.waitKey(0)

-1

In [24]:
hsv_image = cv.cvtColor(img, cv.COLOR_BGR2HSV)

In [25]:
hsv_image[:,:,0] += 20
hsv_image[:,:,1] += 2

In [26]:
cv.imshow("HSV Image", hsv_image)
cv.imwrite("HSV Image.png", hsv_image)
cv.waitKey(0)

-1