In [1]:
import numpy as np

In [2]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [3]:
def signoid_derivative(x):
  return x*(1-x)

In [4]:
input_size = 2
hidden_size = 2
output_size = 1

In [5]:
input_hidden_weight = np.random.rand(input_size, hidden_size)
hidden_output_weight = np.random.rand(hidden_size, output_size)

hidden_bias = np.random.rand(hidden_size)
output_bias = np.random.rand(output_size)

In [6]:
input_hidden_weight

array([[0.96436475, 0.87031316],
       [0.38109487, 0.79581866]])

In [7]:
hidden_output_weight

array([[0.32663777],
       [0.67522399]])

In [8]:
hidden_bias

array([0.22105813, 0.92531288])

In [9]:
output_bias

array([0.24962565])

In [10]:
lr = 0.75
epochs = 10000

In [11]:
train_inp = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
train_out = np.array([[0], [1], [1], [0]])

In [12]:
for i in range(epochs):
  # Feed forward
  hidden_layer_input = np.dot(train_inp, input_hidden_weight) + hidden_bias
  hidden_layer_output = sigmoid(hidden_layer_input)
  output_layer_input = np.dot(hidden_layer_output, hidden_output_weight) + output_bias
  output = sigmoid(output_layer_input)

  # Backpropagation
  error = train_out - output
  output_delta = error * signoid_derivative(output)
  hidden_delta = np.dot(output_delta, hidden_output_weight.T) * signoid_derivative(hidden_layer_output)

  # Update weights
  hidden_output_weight += lr * np.dot(hidden_layer_output.T, output_delta)
  input_hidden_weight += lr * np.dot(train_inp.T, hidden_delta)

  # Print progress
  if i % 1000 == 0:
    print('Epoch:', i, 'Error:', np.mean(np.abs(error)))

print('Done!')


Epoch: 0 Error: 0.4972981414898444
Epoch: 1000 Error: 0.4308342955331658
Epoch: 2000 Error: 0.41900987454439986
Epoch: 3000 Error: 0.4166489408624554
Epoch: 4000 Error: 0.4156548493091252
Epoch: 5000 Error: 0.41510869326247085
Epoch: 6000 Error: 0.41476322561309253
Epoch: 7000 Error: 0.4145248636612106
Epoch: 8000 Error: 0.41435040806731804
Epoch: 9000 Error: 0.41421715512474844
Done!


In [13]:
# New data in numpy array
new_data = np.array([[0, 0], [0, 1], [1, 0],[1,1]])

# Calculate hidden layer output
hidden_layer_input = np.dot(new_data, input_hidden_weight) + hidden_bias
hidden_layer_output = sigmoid(hidden_layer_input)

# Calculate output layer output
output_layer_input = np.dot(hidden_layer_output, hidden_output_weight) + output_bias
output = sigmoid(output_layer_input)

# Print hidden layer output and output layer output
print("Hidden layer output:", hidden_layer_output)
print("Output layer output:", output)


Hidden layer output: [[0.55504058 0.7161234 ]
 [0.00918971 0.99601231]
 [0.99998812 0.99936417]
 [0.9984053  0.99999357]]
Output layer output: [[0.49919204]
 [0.84379474]
 [0.3470869 ]
 [0.34813771]]


In [14]:
# Make a prediction with the trained network
prediction = output
print("Prediction:", prediction)

# Check if the prediction is correct
if (prediction[0] > prediction[1] and train_out[0] > train_out[1]) or (prediction[0] < prediction[1] and train_out[0] < train_out[1]):
  print("Correct prediction!")
else:
  print("Incorrect prediction.")


Prediction: [[0.49919204]
 [0.84379474]
 [0.3470869 ]
 [0.34813771]]
Correct prediction!


In [15]:
# It is called neural network which is seprable and it is learned by using hidden output and sigmoid function then new data output is given and final prediction gets.